### ISSUE TITLE
Setup instructions not fully clear.( ERROR! 'property_folders' is undefined)

### ISSUE THREAD

**Issue by micovery** [carlosfrias/apigee-opdk-playbook-setup-ansible#7]
I am having trouble understanding Step 1 `Setup an Ansible control server and workspace.` from the main readme. 

When I click on the link, it takes me to a new readme file with setup instructions. However, as a new user I am not sure where to to start. It appears as just sections with information. I was expecting a series of well defined steps (even if some of them are optional).

I tried following the usage instructions, (as if it was a series of ordered steps).

First I ran:

```bash
deployer@instance-11:~/apigee-opdk-playbook-setup-ansible/setup$ ansible-galaxy install -r requirements.yml -f
- extracting apigee-opdk-setup-ansible-controller to roles/apigee-opdk-setup-ansible-controller
- apigee-opdk-setup-ansible-controller was installed successfully
- extracting apigee-opdk-modules to roles/apigee-opdk-modules
- apigee-opdk-modules was installed successfully
```

that was successful. 

Then, I ran:

```bash
deployer@instance-11:~/apigee-opdk-playbook-setup-ansible/setup$ ansible-playbook setup.yml 
 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [Setup the Ansible controller] ********************************************

TASK [setup] *******************************************************************
ok: [localhost]
ERROR! 'property_folders' is undefined

```

and got stuck there.

**Comment by carlosfrias** [comment]
Thank you for reporting this. I updated the README to link directly to the Usage section from the initial README. Please update your local instance and let me know the results.

**Comment by micovery** [comment]
@carlosfrias , thanks for updating the link to point directly to the usage section. 

However, that still does not resolve the error  `property_folders' is undefined.

I did a bit of digging and found that the issue is with 

https://github.com/carlosfrias/apigee-opdk-modules/blob/cff7a2f06e83754343706d30ce3619b51c77bf6b/tasks/main.yml#L3-L22


In that file, you are using an ansible `block` with  `when` and `delegate_to` properties . 

i.e.

```yaml
---
- block:
  - name: Find yml property files
    find:
      path: '{{ item }}'
      pattern: '*.yml'
      file_type: file
      hidden: yes
      recurse: no
    with_items: "{{ property_folders }}"
    register: props

  - name: Load variables
    include_vars:
      file: "{{ item.1.path | expanduser }}"
    with_subelements:
    - "{{ props.results }}"
    - files

  delegate_to: localhost
  when: property_folders is defined
```
The way that `block`s work in ansible is that the properties specified at the block level are simply inherited by the children tasks.

This means in this case, that the `Find yml property files` task inherits both the `when`, and `delegage_to` properties, effectively looking like this:

```yaml
  - name: Find yml property files
    find:
      path: '{{ item }}'
      pattern: '*.yml'
      file_type: file
      hidden: yes
      recurse: no
    with_items: "{{ property_folders }}"
    register: props
    delegate_to: localhost
    when: property_folders is defined
```

Now, the way that `when` works .... is that it gets evaluated for each item in a loop .

This means that ansible will try to evaluate first the `with_items` expression (to get the list of items), and then for each item it will evaluate the `when` condition. 

Because of this, if `property_folders` is undefined,  the `with_items` expression evaluation will fail immediately before the `when` expression is even evaluated.

(For more context see this issue: https://github.com/ansible/ansible/issues/20250)

**Comment by carlosfrias** [comment]
I updated the role to separate the logic to each task. It turns out that in turn I also need to check for the definition of props.results but it should allow the module to work with no errors regardless of whether a property_folders is defined. Let me know if you still see any issues.
